<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProducTag($tag) {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->innerJoin('p.tags', 't')
            ->where('t.nom=:tag')
            ->orderBy('t.nom', 'ASC')
            ->setParameter('tag', $tag)
            ->getQuery()
            ->getResult();
    }



}
